from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QFileDialog
from PyQt5.QtGui import QPixmap

from DnDTableWidgetStatsItem import DnDTableWidgetStatsItem

class DnDItemPropertyEditor(QWidget):
    def __init__(self):
        super(DnDItemPropertyEditor, self).__init__()
        self.setupUi(self)

        # After Setup
        self.setCustomTypeItemField()
        self.setCustomRarityItemField()
        self.labelImageItem.setPixmap(QPixmap("Images/icon.png"))

        self.initTriggers()

    def initTriggers(self):
        self.comboBoxTypeItem.currentIndexChanged.connect(self.handlerChangedTypeItem)
        self.comboBoxRarityItem.currentIndexChanged.connect(self.setCustomRarityItemField)
        self.openImageItemButton.clicked.connect(self.openImage)

    def handlerChangedTypeItem(self):
        self.setCustomTypeItemField()
        self.tableWidgetStatsItem.setStats(self.comboBoxTypeItem.currentText())

    def openFileDialog(self, parent=None):
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly  # Устанавливаем режим только для чтения
        file_path, _ = QFileDialog.getOpenFileName(parent, "Выберите файл", "",
                                                   "Все файлы (*);;Изображения (*.png)", options=options)

        return file_path if file_path else None

    def openImage(self):
        print("open")
        path = self.openFileDialog()
        print(path)
        if path:
            self.labelImageItem.setPixmap(QPixmap(path))

    def setCustomTypeItemField(self):
        self.lineEditCustomTypeItem.setHidden(self.comboBoxTypeItem.currentText() != "Custom Type")

    def setCustomRarityItemField(self):
        self.lineEditCustomRarityItem.setHidden(self.comboBoxRarityItem.currentText() != "Custom Rarity")

    def setupUi(self, DnDItemPropertyEditor):
        DnDItemPropertyEditor.setObjectName("DnDItemPropertyEditor")
        DnDItemPropertyEditor.resize(750, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DnDItemPropertyEditor.sizePolicy().hasHeightForWidth())
        DnDItemPropertyEditor.setSizePolicy(sizePolicy)
        DnDItemPropertyEditor.setMinimumSize(QtCore.QSize(750, 750))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DnDItemPropertyEditor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DnDItemPropertyEditor)
        self.label.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditNameItem = QtWidgets.QLineEdit(DnDItemPropertyEditor)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditNameItem.setFont(font)
        self.lineEditNameItem.setObjectName("lineEditNameItem")
        self.horizontalLayout.addWidget(self.lineEditNameItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(DnDItemPropertyEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.openImageItemButton = QtWidgets.QPushButton(DnDItemPropertyEditor)
        self.openImageItemButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.openImageItemButton.setFont(font)
        self.openImageItemButton.setObjectName("openImageItemButton")
        self.horizontalLayout_2.addWidget(self.openImageItemButton)
        self.line = QtWidgets.QFrame(DnDItemPropertyEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.labelImageItem = QtWidgets.QLabel(DnDItemPropertyEditor)
        self.labelImageItem.setMinimumSize(QtCore.QSize(150, 150))
        self.labelImageItem.setMaximumSize(QtCore.QSize(150, 150))
        self.labelImageItem.setText("")
        self.labelImageItem.setPixmap(QtGui.QPixmap(
            "C:\\Users\\Mr. Slime\\Desktop\\DnD Item Creator\\UIs\\../../DnD Tools/Resources/Images/Icons/icon.png"))
        self.labelImageItem.setScaledContents(True)
        self.labelImageItem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImageItem.setObjectName("labelImageItem")
        self.horizontalLayout_2.addWidget(self.labelImageItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(DnDItemPropertyEditor)
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEditBriefHint = QtWidgets.QLineEdit(DnDItemPropertyEditor)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditBriefHint.setFont(font)
        self.lineEditBriefHint.setObjectName("lineEditBriefHint")
        self.horizontalLayout_3.addWidget(self.lineEditBriefHint)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxTypeItem = QtWidgets.QComboBox(DnDItemPropertyEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTypeItem.sizePolicy().hasHeightForWidth())
        self.comboBoxTypeItem.setSizePolicy(sizePolicy)
        self.comboBoxTypeItem.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBoxTypeItem.setFont(font)
        self.comboBoxTypeItem.setObjectName("comboBoxTypeItem")
        self.comboBoxTypeItem.addItem("")
        self.comboBoxTypeItem.addItem("")
        self.comboBoxTypeItem.addItem("")
        self.comboBoxTypeItem.addItem("")
        self.comboBoxTypeItem.addItem("")
        self.comboBoxTypeItem.addItem("")
        self.comboBoxTypeItem.addItem("")
        self.gridLayout.addWidget(self.comboBoxTypeItem, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(DnDItemPropertyEditor)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(DnDItemPropertyEditor)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.comboBoxRarityItem = QtWidgets.QComboBox(DnDItemPropertyEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxRarityItem.sizePolicy().hasHeightForWidth())
        self.comboBoxRarityItem.setSizePolicy(sizePolicy)
        self.comboBoxRarityItem.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBoxRarityItem.setFont(font)
        self.comboBoxRarityItem.setObjectName("comboBoxRarityItem")
        self.comboBoxRarityItem.addItem("")
        self.comboBoxRarityItem.addItem("")
        self.comboBoxRarityItem.addItem("")
        self.comboBoxRarityItem.addItem("")
        self.comboBoxRarityItem.addItem("")
        self.comboBoxRarityItem.addItem("")
        self.comboBoxRarityItem.addItem("")
        self.comboBoxRarityItem.addItem("")
        self.gridLayout.addWidget(self.comboBoxRarityItem, 0, 4, 1, 1)
        self.lineEditCustomTypeItem = QtWidgets.QLineEdit(DnDItemPropertyEditor)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditCustomTypeItem.setFont(font)
        self.lineEditCustomTypeItem.setObjectName("lineEditCustomTypeItem")
        self.gridLayout.addWidget(self.lineEditCustomTypeItem, 0, 2, 1, 1)
        self.lineEditCustomRarityItem = QtWidgets.QLineEdit(DnDItemPropertyEditor)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditCustomRarityItem.setFont(font)
        self.lineEditCustomRarityItem.setObjectName("lineEditCustomRarityItem")
        self.gridLayout.addWidget(self.lineEditCustomRarityItem, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(DnDItemPropertyEditor)
        self.label_7.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.line_2 = QtWidgets.QFrame(DnDItemPropertyEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.plainTextEditDescriptionItem = QtWidgets.QPlainTextEdit(DnDItemPropertyEditor)
        self.plainTextEditDescriptionItem.setMinimumSize(QtCore.QSize(0, 170))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEditDescriptionItem.setFont(font)
        self.plainTextEditDescriptionItem.setPlainText("")
        self.plainTextEditDescriptionItem.setObjectName("plainTextEditDescriptionItem")
        self.verticalLayout.addWidget(self.plainTextEditDescriptionItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(DnDItemPropertyEditor)
        self.label_8.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.line_3 = QtWidgets.QFrame(DnDItemPropertyEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.tableWidgetStatsItem = DnDTableWidgetStatsItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidgetStatsItem.setFont(font)
        self.tableWidgetStatsItem.setObjectName("tableWidgetStatsItem")
        self.verticalLayout_2.addWidget(self.tableWidgetStatsItem)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.clearListButton = QtWidgets.QPushButton(DnDItemPropertyEditor)
        self.clearListButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearListButton.setFont(font)
        self.clearListButton.setObjectName("clearListButton")
        self.horizontalLayout_6.addWidget(self.clearListButton)
        self.addItemButton = QtWidgets.QPushButton(DnDItemPropertyEditor)
        self.addItemButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addItemButton.setFont(font)
        self.addItemButton.setObjectName("addItemButton")
        self.horizontalLayout_6.addWidget(self.addItemButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(DnDItemPropertyEditor)
        QtCore.QMetaObject.connectSlotsByName(DnDItemPropertyEditor)

    def retranslateUi(self, DnDItemPropertyEditor):
        _translate = QtCore.QCoreApplication.translate
        DnDItemPropertyEditor.setWindowTitle(_translate("DnDItemPropertyEditor", "Form"))
        self.label.setText(_translate("DnDItemPropertyEditor", "Name Item"))
        self.label_4.setText(_translate("DnDItemPropertyEditor", "Image Item"))
        self.openImageItemButton.setText(_translate("DnDItemPropertyEditor", "Open"))
        self.label_6.setText(_translate("DnDItemPropertyEditor", "Brief hint"))
        self.comboBoxTypeItem.setItemText(0, _translate("DnDItemPropertyEditor", "Weapons"))
        self.comboBoxTypeItem.setItemText(1, _translate("DnDItemPropertyEditor", "Medicines"))
        self.comboBoxTypeItem.setItemText(2, _translate("DnDItemPropertyEditor", "Components"))
        self.comboBoxTypeItem.setItemText(3, _translate("DnDItemPropertyEditor", "Artifacts"))
        self.comboBoxTypeItem.setItemText(4, _translate("DnDItemPropertyEditor", "Tools"))
        self.comboBoxTypeItem.setItemText(5, _translate("DnDItemPropertyEditor", "Clothes"))
        self.comboBoxTypeItem.setItemText(6, _translate("DnDItemPropertyEditor", "Custom Type"))
        self.label_2.setText(_translate("DnDItemPropertyEditor", "Type Item"))
        self.label_3.setText(_translate("DnDItemPropertyEditor", "Rarity"))
        self.comboBoxRarityItem.setItemText(0, _translate("DnDItemPropertyEditor", "Ordinary"))
        self.comboBoxRarityItem.setItemText(1, _translate("DnDItemPropertyEditor", "Unusual"))
        self.comboBoxRarityItem.setItemText(2, _translate("DnDItemPropertyEditor", "Rare"))
        self.comboBoxRarityItem.setItemText(3, _translate("DnDItemPropertyEditor", "Very rare"))
        self.comboBoxRarityItem.setItemText(4, _translate("DnDItemPropertyEditor", "Epic"))
        self.comboBoxRarityItem.setItemText(5, _translate("DnDItemPropertyEditor", "Legendary"))
        self.comboBoxRarityItem.setItemText(6, _translate("DnDItemPropertyEditor", "Mythical"))
        self.comboBoxRarityItem.setItemText(7, _translate("DnDItemPropertyEditor", "Custom Rarity"))
        self.label_7.setText(_translate("DnDItemPropertyEditor", "Description"))
        self.label_8.setText(_translate("DnDItemPropertyEditor", "Stats"))
        self.clearListButton.setText(_translate("DnDItemPropertyEditor", "Clear List"))
        self.addItemButton.setText(_translate("DnDItemPropertyEditor", "Add Item"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    widget = DnDItemPropertyEditor()
    widget.show()
    sys.exit(app.exec_())
